const { create, Client } = require('@open-wa/wa-automate')
const { color, options } = require('./tools')
const { loader } = require('./function')
const msgHandler = require('./nawaf.js')
const figlet = require('figlet')
const canvas = require('discord-canvas')
const { ownerBot } = require('./config.json')
const fs = require('fs-extra')
